# SPDX-FileCopyrightText: © 2025 Secret Dimension, Inc. <info@secretdimension.com>. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: Push

on:
  push:

jobs:
  build:
    name: Build & Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Poetry Check
        run: poetry check

      - name: Poetry Install
        run: poetry install --no-interaction

      - name: Build
        run: poetry build

      - name: Pytype
        run: poetry run pytype

  generate-readme:
    name: Generate Readme
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"

      - name: Poetry Install
        run: poetry install --with dev --no-interaction

      - name: Generate Readme
        run: poetry poe genreadme

        # Ensure README.md will pass pre-commit checks
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --files README.me end-of-file-fixer
        continue-on-error: true

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Update README"
          file_pattern: "README.md"
